classname: pipelines.wind_cube_profile_sta.pipeline.WindCubeProfile

triggers:
  - .*\.sta.7z

retriever:
  path: pipelines/wind_cube_profile_sta/config/retriever.yaml

dataset:
  path: pipelines/wind_cube_profile_sta/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
