classname: pipelines.lidar_disdrometer.pipeline.LidarDisdrometer

triggers:
  - .*sa1.ld.z02.*\.dat

retriever:
  path: pipelines/lidar_disdrometer/config/retriever.yaml

dataset:
  path: pipelines/lidar_disdrometer/config/dataset.yaml
  overrides:
    /attrs/location_id: sa1
    /attrs/location_meaning: ""
    /attrs/dataset_name: ldis_z02

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
