attrs:
  title: Laser Disdrometer Pipeline
  dataset_name: lidar_z01
  description: AWAKEN Laser Disdrometer ingest pipeline
  institution: Atmosphere to Electrons
  #location: North Slope, AK
  location_id: aml
  data_level: b0
  # qualifier: lidar
  # temporal: 10s
  conventions: MHKiT-Cloud Data Standards v1.0

coords:
  time:
    attrs:
      description: ""
      long_name: Time (UTC)
      units: Seconds since 1970-01-01 00:00:00
    dims:
      - time
    dtype: datetime64[s]
data_vars:
  amplitude:
    attrs:
      description: Signal amplitude of laserband
      long_name: Amplitude
      units: dB
    dims:
      - time
    dtype: float
  heating_current:
    attrs:
      description: Heating current sent to sensor body
      long_name: Heating Current
      units: A
    dims:
      - time
    dtype: float
  kinetic_energy:
    attrs:
      description: Kinetic energy of precipitation
      long_name: Kinetic Energy
      units: J
      valid_min: 0.0
    dims:
      - time
    dtype: float
  n_particles:
    attrs:
      description: Number of detected particles
      long_name: N Particles
      units: count
    dims:
      - time
    dtype: int
  optics_status:
    attrs:
      description: ""
      long_name: Optics Status
      units: "1"
    dims:
      - time
    dtype: str
  precipitation_intensity:
    attrs:
      description: ""
      long_name: Precipitation Intensity
      units: mm/h
      valid_min: 0.0
    dims:
      - time
    dtype: float
  radar_reflectivity:
    attrs:
      description: ""
      long_name: Radar Reflectivity
      units: dBZ
    dims:
      - time
    dtype: float
  sensor_temperature:
    attrs:
      description: Temperature in sensor body
      long_name: Sensor Temperature
      units: degC
    dims:
      - time
    dtype: float
  sensor_voltage:
    attrs:
      description: ""
      long_name: Sensor Voltage
      units: V
    dims:
      - time
    dtype: float
  snow_intensity:
    attrs:
      description: ""
      long_name: Snow Intensity
      units: mm/h
    dims:
      - time
    dtype: float
  total_precipitation:
    attrs:
      description: ""
      long_name: Total Precipitation
      units: mm/h
      valid_min: 0.0
    dims:
      - time
    dtype: float
  visibility:
    attrs:
      description: ""
      long_name: Visibility
      units: m
    dims:
      - time
    dtype: float
  weather_code_metar:
    attrs:
      description: ""
      long_name: Weather Code Metar
      units: "1"
    dims:
      - time
    dtype: str
  weather_code_nws:
    attrs:
      description: ""
      long_name: Weather Code Nws
      units: "1"
    dims:
      - time
    dtype: str
  weather_code_synop:
    attrs:
      description: ""
      long_name: Weather Code Synop
      units: "1"
    dims:
      - time
    dtype: str

  latitude:
    data: 71.323
    dims: []
    dtype: float
    attrs:
      long_name: "North latitude"
      standard_name: "latitude"
      comment: "Recorded lattitude at the instrument location"
      units: "degree_N"

  longitude:
    data: -156.609
    dims: []
    dtype: float
    attrs:
      long_name: "East longitude"
      standard_name: "longitude"
      comment: "Recorded longitude at the instrument location"
      units: "degree_E"

  altitude:
    data: 4000.0
    dims: []
    dtype: float
    attrs:
      long_name: "Altitude"
      comment: "Recorded altitude at the instrument location"
      units: m
