classname: pipelines.met_campbell.pipeline.MET

triggers:
  - .*sa5\.met\.z01.*\.txt
  - .*sa5.met_z01.*\.txt

retriever:
  path: pipelines/met_campbell/config/retriever.yaml

dataset:
  path: pipelines/met_campbell/config/dataset.yaml
  overrides:
    /attrs/location_id: sa5
    /attrs/location_meaning: "Site A5"
    /attrs/dataset_name: met_z01
    /data_vars/longitude/data: -97.381548
    /data_vars/latitude/data: 36.361762

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
