classname: pipelines.met_campbell.pipeline.MET

triggers:
  - .*sa1\.met\.z01.*\.txt
  - .*sa1.met_z01.*\.txt

retriever:
  path: pipelines/met_campbell/config/retriever.yaml

dataset:
  path: pipelines/met_campbell/config/dataset.yaml
  overrides:
    /attrs/location_id: sa1
    /attrs/location_meaning: "Site A1"
    /attrs/dataset_name: met_z01
    /data_vars/longitude/data: -97.405089
    /data_vars/latitude/data: 36.362111

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
