classname: pipelines.met_campbell.pipeline.MET

triggers:
  - .*sb.met_z01.*\.txt

retriever:
  path: pipelines/met_campbell/config/retriever.yaml

dataset:
  path: pipelines/met_campbell/config/dataset.yaml
  overrides:
    /attrs/location_id: sb
    /attrs/location_meaning: "Site B"
    /attrs/dataset_name: met_z01

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
