classname: pipelines.met_campbell.pipeline.MET

triggers:
  - .*sa3.met_z01.*\.txt

retriever:
  path: pipelines/met_campbell/config/retriever.yaml

dataset:
  path: pipelines/met_campbell/config/dataset.yaml
  overrides:
    /attrs/location_id: sa3
    /attrs/location_meaning: "Site A3"
    /attrs/dataset_name: met_z01

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
