classname: pipelines.assist.pipeline.Assist

triggers:
  - .*assist.z02.*\.cdf

retriever:
  path: pipelines/assist/config/retriever.yaml

dataset:
  path: pipelines/assist/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
