classname: pipelines.lidar_halo_xrp.pipeline.LidarHaloXrp

triggers:
  - .*rt2\.lidar\.z01\.00.*\.hpl

retriever:
  path: pipelines/lidar_halo_xrp/config/retriever.yaml

dataset:
  path: pipelines/lidar_halo_xrp/config/dataset.yaml
  overrides:
    /attrs/location_id: rt2
    /attrs/location_meaning: "Instrumented turbine G02, forward-facing"
    /attrs/dataset_name: lidar_z01
    /data_vars/longitude/data: -97.406097
    /data_vars/latitude/data: 36.381363

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
