classname: pipelines.wind_cube_profile_rtd.pipeline.WindCubeProfile

triggers:
  - .*WLS.*\.rtd.7z

retriever:
  path: pipelines/wind_cube_profile_rtd/config/retriever.yaml

dataset:
  path: pipelines/wind_cube_profile_rtd/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
